// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu8vPQEjwYEk4IOSxMTNUCDalqnvs5RJg',
    appId: '1:723819182757:web:0a0e9a3c145c82424b2b4c',
    messagingSenderId: '723819182757',
    projectId: 'testing-cli-31359',
    authDomain: 'testing-cli-31359.firebaseapp.com',
    storageBucket: 'testing-cli-31359.appspot.com',
    measurementId: 'G-8K6MP990ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP0YDMwLwNM6Ea3wYG4U28NhOVW5vjaHc',
    appId: '1:723819182757:android:ce7c7e279599be194b2b4c',
    messagingSenderId: '723819182757',
    projectId: 'testing-cli-31359',
    storageBucket: 'testing-cli-31359.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIwQBd-Yg2elnLQGb5arreH9d_aUynIik',
    appId: '1:723819182757:ios:682f834c67048d314b2b4c',
    messagingSenderId: '723819182757',
    projectId: 'testing-cli-31359',
    storageBucket: 'testing-cli-31359.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIwQBd-Yg2elnLQGb5arreH9d_aUynIik',
    appId: '1:723819182757:ios:682f834c67048d314b2b4c',
    messagingSenderId: '723819182757',
    projectId: 'testing-cli-31359',
    storageBucket: 'testing-cli-31359.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu8vPQEjwYEk4IOSxMTNUCDalqnvs5RJg',
    appId: '1:723819182757:web:b1a2a9622491352c4b2b4c',
    messagingSenderId: '723819182757',
    projectId: 'testing-cli-31359',
    authDomain: 'testing-cli-31359.firebaseapp.com',
    storageBucket: 'testing-cli-31359.appspot.com',
    measurementId: 'G-P04XPZ3Z8K',
  );
}
